name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4 # Upgrade to v4 for better support

      - name: Dependency Review
        uses: actions/dependency-review-action@v4 # Upgrade to v4
        with:
          # Use 'all' or 'runtime' to ensure the test package is caught
          deny-licenses: LGPL-2.0, BSD-2-Clause
          # Setting this to 'low' ensures it catches almost any vulnerability
          fail-on-severity: low
